import firebase_app from "../firebaseConfig";
import {
  getFirestore,
  collection,deleteDoc,doc,where, query, getDocs
} from "firebase/firestore";

const db = getFirestore(firebase_app);
const deleteData = async (docId: string,collections:string) => {
  try {
    // Define your Firestore instance

    // Specify your collection name
    const collectionName = collections;

    // Query the collection to find the document with your custom ID
    const q = query(collection(db, collectionName), where("id", "==", docId));
    const querySnapshot = await getDocs(q);

    if (!querySnapshot.empty) {
      // Get the auto-generated Firebase unique ID from the first document found
      const autoGeneratedId = querySnapshot.docs[0].id;

      // Delete the document using the auto-generated ID
      await deleteDoc(doc(db, collectionName, autoGeneratedId));

      console.log("Entire Document has been deleted successfully.");
      // loadDocuments();
    } else {
      console.log("Document not found for deletion:", docId);
    }
  } catch (error) {
    console.error("Error deleting document:", error);
  }
};

export default deleteData;