import firebase_app from "../firebaseConfig";
import {
  getFirestore,
  collection,deleteDoc,doc,where, query, getDocs , updateDoc
} from "firebase/firestore";
import { Timestamp } from "firebase/firestore";
interface ResultsData {
  competitionName: string;
  candidatesCount: number;
  admittedCount: number;
  sessionYear: number;
  successRate: number;
  bannerImage: File;
  date: Timestamp;
   id:string;
}

interface ExamsData {
  competitionName: string;
  bannerImage: File;
  subjects: string;
  courseList: string;
   id:string;
}

interface AnnoncesData {
  date: Timestamp;
  Title: string;
  bannerImage: File;
  description: string;
  usefulLinks: string;
   id:string;
}

type CollectionData = ResultsData | ExamsData | AnnoncesData;


const db = getFirestore(firebase_app);

const updateData = async (docId: string,collections:string,data:CollectionData) => {
  try {
    // Define your Firestore instance

    // Specify your collection name
    const collectionName = collections;

    // Query the collection to find the document with your custom ID
    const q = query(collection(db, collectionName), where("id", "==", docId));
    const querySnapshot = await getDocs(q);

    if (!querySnapshot.empty) {
      // Get the auto-generated Firebase unique ID from the first document found
      const autoGeneratedId = querySnapshot.docs[0].id;

      // Delete the document using the auto-generated ID
    // await updateDoc(docRef, data);
        let docRef = doc(db, collectionName, autoGeneratedId)
        delete data.bannerImage;
        await updateDoc(docRef, { ...data});
        

      console.log(" Document has been update successfully.");
      // loadDocuments();
    } else {
      console.log("Document not found for update:", docId);
    }
  } catch (error) {
    console.error("Error deleting document:", error);
  }
};

export default updateData;